apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  namespace: exercise-01
  labels:
    app: wpblog
    component: database
spec:
  selector:
    matchLabels:
      component: database
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: wpblog
        component: database
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:latest
        ports:
        - containerPort: 3306
          name: mysql
        env: # Vars from https://hub.docker.com/r/bitnami/mariadb
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: blogconfig
              key: db-blog-name
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: blogconfig
              key: db-blog-user
        - name: MARIADB_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: blogsecrets
              key: db-blog-password