apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "lemp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "lemp.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: data
          hostPath:
            path: /app/php-sample-app/
        - name: config-vol
          configMap:
            name: vol-config-map
            items:
              - key: conf
                path: myapp.conf
      initContainers:
        - name: download-php
          image: busybox
          command: 
            - 'wget'
            - '-O'
            - '/app/php-sample-app/index.php'
            - 'https://raw.githubusercontent.com/bitnami-labs/k8s-training-resources/master/php-sample-app/index.php'
          volumeMounts:
            - name: data
              mountPath: /app/php-sample-app/
      containers:       
        - name: php
          image: bitnami/php-fpm
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/php-sample-app/
        - name: {{ .Chart.Name }}
#          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          image: "bitnami/nginx"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config-vol
              mountPath: /bitnami/nginx/conf/vhosts
            - name: data
              mountPath: /app/php-sample-app/
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}      
