# Exercise 2 of session 1: Mariadb deployment
# Pedro Ignacio Respaldiza Hidalgo (aka IÃ±aki Respaldiza)
# K8s Training user: pedro_respaldiza
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: exercise-02
  labels:
    app: wordpress
    type: frontend
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  rules:
  - host: wordpress-exercise-02.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress-service
          servicePort: http-sv-port
